runtime: go
service: notify
env: flex # w000tzers

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  CALENDAR_APP: "https://calendarcron.appspot.com/"
  CALENDAR_APP_PING: "https://calendarcron.appspot.com/event/ping"
  CALENDAR_APP_CHANGED: "https://calendarcron.appspot.com/event/ping"
  NOTIFY_EXPIRE_AFTER: "3600"
