runtime: go
service: notify
env: flex # w000tzers

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  APP: "https://calendar-cron.appspot.com/"
  APP_PING: "https://calendar-cron.appspot.com/event/ping"
  APP_CHANGED: "https://calendar-cron.appspot.com/event/ping"
