runtime: go
api_version: go1
service: default

handlers:
# root
- url: /
  static_files: index.html
  upload: index.html
- url: /static/
  static_dir: static

# serve everything from the Go App
- url: /.*
  script: _go_app
# Favicon.  Without this, the browser hits this once per page view.
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
